# fly.toml file generated for df-hackathon-lighthouse-team-illumin8 on 2024-07-30T16:58:29+01:00

app = "df-hackathon-lighthouse-team-illumin8"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "lhr"
processes = []

[env]
  PORT = "8080"
	DB_URI = "mongodb+srv://Afrodyta-lighthouse:2eIocfVvh6h8NAbT@mongo-db-practice.lcep4um.mongodb.net/lighthouse-illumin8"
	SECRET="secret_dev"
	NODE_ENV = "production"
	HOST = "0.0.0.0"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
